CREATE TABLE Anagrafica (
IDanagrafica INT IDENTITY NOT NULL PRIMARY KEY,
Cognome NVARCHAR(50) NOT NULL,
Nome NVARCHAR(50) NOT NULL,
Indirizzo NVARCHAR(100) NOT NULL,
Citta NVARCHAR(50) NOT NULL,
CAP NVARCHAR(5) NOT NULL,
Cod_Fisc NVARCHAR(16) NOT NULL
)
